apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - git@github.com:talos-systems/cluster-api-provider-metal/config/default?ref=master
images:
  - name: controller
    newName: docker.io/autonomy/cluster-api-metal-controller
    newTag: 043d44f
