apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ./bases/metal-controller-manager
  - ./bases/metal-metadata-server
resources:
  - namespace.yaml
namespace: arges-system
commonLabels:
  arges: v1alpha1
