apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../config
resources:
  - environments.yaml
patchesJson6902:
  - target:
      group: metal.arges.dev
      version: v1alpha1
      kind: Environment
      name: default
      namespace: arges-system
    path: default_environment_patch.yaml
